package modelo.conteudo;

public enum Pericias {

    ARTES, ATLETISMO, CIENCIAS, ESCUTAR, FURTIVIDADE,
    HISTORIA, INTIMIDACAO, INVESTIGACAO, LABIA, LINGUAS,
    LUTAR, MECANICA, MEDICINA, PERCEPCAO, PILOTAGEM,
    PONTARIA, PRESTIDIGITACAO, PSICOLOGIA, SOBREVIVENCIA, TECNOLOGIA;
}
